name: alive

on:
  schedule:
    - cron: '15 5 1 * *'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          date +%m > .alive
          git add .alive
          git config user.name github
          git config user.email actions@github.com
          git commit -m "`date +%m`"
          git push
