name: build-alpine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: robusta
        uses: actions/checkout@v3
        with:
          repository: AICafe1/robusta
          token: ${{ secrets.PASS }}
          ref: build

      - name: data
        uses: actions/checkout@v3
        with:
          repository: AICafe1/robusta-data
          token: ${{ secrets.PASS }}
          path: data

      - name: src
        uses: actions/checkout@v3
        with:
          repository: AICafe1/robusta-src
          token: ${{ secrets.PASS }}
          path: src

      - name: Node.js Alpine Build
        uses: docker://node:18-alpine
        run: |
          npm ci
          npm run b-alp
          cd data; npm ci
          npm run b-alp
          cd ..
          node src/license/private.ts --year=1 LICENSE.key
          bin/robustalp abi.js
          bin/robustalp --mode=manage
          ls -l robusta.sqlite

      - run: |
          mv bin/robustalp robusta
          mv data/bin/rdatalp rdata
          chmod +x robusta rdata
          tar -czvf robusta-alpine.tgz robusta
          tar -czvf rdata-alpine.tgz rdata

      - uses: actions/upload-artifact@v3
        with:
          name: robusta
          path: robusta

      - uses: actions/upload-artifact@v3
        with:
          name: rdata
          path: rdata

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.tgz"
