name: build-linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: robusta
        uses: actions/checkout@v3
        with:
          repository: AICafe/robusta
          ref: main
          token: ${{ secrets.PASS }}

      - run: ls -l
