name: build-linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: robusta
        uses: actions/checkout@v3
        with:
          repository: AICafe1/robusta
          token: ${{ secrets.PASS }}

      - name: data
        uses: actions/checkout@v3
        with:
          repository: AICafe1/robusta-data
          token: ${{ secrets.PASS }}
          path: data

      - name: src
        uses: actions/checkout@v3
        with:
          repository: AICafe1/robusta-src
          token: ${{ secrets.PASS }}
          path: src

      - name: Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: cd data; npm install

      - run: npm run b-lnx
      - run: cd data; npm run b-lnx

      - uses: actions/upload-artifact@v3
        with:
          name: robusta
          path: bin/robusta

      - uses: actions/upload-artifact@v3
        with:
          name: data
          path: data/bin/rdata
