name: build-macos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: robusta
        uses: actions/checkout@v3
        with:
          repository: AICafe1/robusta
          token: ${{ secrets.PASS }}
          ref: build

      - name: data
        uses: actions/checkout@v3
        with:
          repository: AICafe1/robusta-data
          token: ${{ secrets.PASS }}
          path: data

      - name: src
        uses: actions/checkout@v3
        with:
          repository: AICafe1/robusta-src
          token: ${{ secrets.PASS }}
          path: src

      - name: Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: cd data; npm ci

      - run: npm run b-osx
      - run: cd data; npm run b-osx

      - run: node src/license/private.ts --year=1 LICENSE.key
      - run: bin/robustx abi.js
      - run: bin/robustx --mode=manage
      - run: ls -l robusta.sqlite

      - run: |
          mv bin/robustx robusta
          mv data/bin/rdatx rdata
          chmod +x robusta rdata
          tar -czvf robusta-macos.tgz robusta
          tar -czvf rdata-macos.tgz rdata

      - uses: actions/upload-artifact@v3
        with:
          name: robusta
          path: robusta

      - uses: actions/upload-artifact@v3
        with:
          name: rdata
          path: rdata

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.tgz"
