name: data

on:
  schedule:
    - cron: '1 1 * * 1-5'
    - cron: '15 9 * * 1-5'
    - cron: '15 9 * * 6'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: VSCode
        default: false
      group:
        type: choice
        description: Run group
        options:
          - all
          - weekly
          - morning
          - daily
          - vnqa

env:
  weekly: ${{ github.event.schedule == '15 9 * * 6' || github.event.inputs.group == 'weekly' || github.event.inputs.group == 'all' }}
  morning: ${{ github.event.schedule == '1 1 * * 1-5' || github.event.inputs.group == 'morning' || github.event.inputs.group == 'all' }}
  daily: ${{ github.event.schedule == '15 9 * * 1-5' || github.event.inputs.group == 'daily' || github.event.inputs.group == 'all' }}
  vnqa: ${{ github.event.schedule == '15 9 * * 1-5' || github.event.inputs.group == 'vnqa' || github.event.inputs.group == 'all' }}

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      REPO: https://github.com/AICafe1/robusta-server/releases/download

    steps:
      # Base Steps
      - name: robusta
        uses: actions/checkout@v6
        with:
          repository: AICafe1/robusta
          token: ${{ secrets.PASS }}

      - name: data
        uses: actions/checkout@v6
        with:
          repository: AICafe1/robusta-data
          token: ${{ secrets.PASS }}
          path: data

      - name: src
        uses: actions/checkout@v6
        with:
          repository: AICafe1/robusta-src
          token: ${{ secrets.PASS }}
          path: src

      - name: Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: npm i --omit=dev; cd data; npm i @duckdb/node-api better-sqlite3 knex@2.5.1 --no-save

      - name: PreVSCode
        if: ${{ inputs.debug == true }}
        env:
          DNSE_KEY: ${{ secrets.DNSE_KEY }}
          DNSE_SEC: ${{ secrets.DNSE_SEC }}
          ZP: ${{ secrets.ZIP }}
        uses: dacdoan/action-debug-vscode@main

      - name: VSCode
        if: ${{ inputs.debug == true }}
        env:
          DNSE_KEY: ${{ secrets.DNSE_KEY }}
          DNSE_SEC: ${{ secrets.DNSE_SEC }}
          ZP: ${{ secrets.ZIP }}
        uses: fawazahmed0/action-debug-vscode@main

      - name: Chrome curl
        run: cd /usr/local/bin; wget -q -O - https://github.com/AICafe1/robusta-server/releases/download/v1.0.2/chrome.tgz | tar -xz

      - name: Python 3
        if: env.vnqa == 'true'
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Pip
        if: env.vnqa == 'true'
        run: cd data; pip install -q -r requirements.txt

      - name: vnd
        run: |
          mkdir env
          mkdir csv/vnd
          cd csv/vnd
          [ -s daily.zip ] || wget -q $REPO/v1.0.0/daily.zip || true
          [ -s daily.zip ] || wget -q $REPO/v1.0.2/daily.zip
          unzip -qP ${{ secrets.ZIP }} daily.zip
          rm daily.zip

      # VN Weekly
      - name: VN Weekly
        if: env.weekly == 'true'
        run: |
          node data/download -m vnd -v
          node data/download

      # VN Morning
      - name: VN Morning
        if: env.morning == 'true'
        run: |
          node data/download -m vnd -v
          node data/download -t event,minute,review,value

      # VN Daily
      - name: VN Daily
        if: env.daily == 'true'
        run: |
          node data/download -m vnd -v
          node data/download
          node data/download/vn/helpers -t f | xargs -I {} node data/download -t index -s {}
          node data/download/vn/helpers -t e | xargs -I {} node data/download -t daily -s {}

      # VN
      - name: VN Audit
        if: env.morning == 'true' || env.daily == 'true' || env.weekly == 'true'
        run: |
          ls error.sh && node data/error.js && sh rerun.sh && rm rerun.sh || echo 1
          ls error.sh && node data/error.js && sh rerun.sh && rm rerun.sh || echo 2
          ls error.sh && node data/error.js && sh rerun.sh && rm rerun.sh || echo 3
          node data/audit

      # Robusta push
      - name: Audit
        id: audit
        if: github.event_name == 'schedule' || github.event.inputs.group != 'vnqa'
        run: cat audit.txt && (echo 'r=false' > $GITHUB_OUTPUT) || (echo 'r=true' > $GITHUB_OUTPUT)

      - name: Notify
        if: steps.audit.outputs.r == 'false'
        run: node data/audit/notify.js

      - name: Push
        run: |
          git config user.name github
          git config user.email actions@github.com
          git add csv
          [[ ! -f audit.txt ]] || grep -Eo '^[^ ]+' audit.txt | xargs git reset
          git commit -m "csv" || echo ""
          git push

      # Robusta Release
      - name: Robusta Release
        run: |
          git restore csv
          tar -czf vn.tgz csv/vn
          zip -P ${{ secrets.ZIP }} vn.tgz.zip vn.tgz
          node data/download/vnd/v.cjs
          cd csv/vnd
          zip -P ${{ secrets.ZIP }} daily.zip *.sqlite
          mv daily.zip ../..
          cd ../..
          node data/download/vnd/io.cjs -d c
          node data/download/vnd/v.cjs
          cd csv/vnd
          zip -P ${{ secrets.ZIP }} daily2.zip *.sqlite
          mv daily2.zip ../..

      - name: Robusta Release v1.0.0
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v1.0.0
          files: |
            daily.zip
            daily2.zip
            vn.tgz.zip

      - name: Robusta Release v1.0.2
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v1.0.2
          files: |
            daily.zip
            daily2.zip
            vn.tgz.zip

      # VNQA
      - name: VNQA
        if: env.vnqa == 'true'
        uses: actions/checkout@v6
        with:
          repository: AICafe1/vnqa
          token: ${{ secrets.PASS }}
          path: vnqa

      - name: VNQA Release
        if: env.vnqa == 'true'
        run: |
          cd vnqa
          git config user.name github
          git config user.email actions@github.com
          cd ..
          sh data/vnqa/data.sh
