name: debug

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: robusta
        if: github.event_name == 'schedule' || github.event.inputs.group != 'feather'
        uses: actions/checkout@v6
        with:
          repository: AICafe1/robusta
          token: ${{ secrets.PASS }}

      - name: data
        uses: actions/checkout@v6
        with:
          repository: AICafe1/robusta-data
          token: ${{ secrets.PASS }}
          path: data

      - name: Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: cd data; npm install

      - name: Chrome curl
        run: cd /usr/local/bin; wget -q -O - https://github.com/AICafe1/robusta-server/releases/download/v1.0.2/chrome.tgz | tar -xz

      - name: Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - run: cd data; pip install -q -r requirements.txt

      - uses: fawazahmed0/action-debug-vscode@main
