name: Intraday Data

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: VSCode
        default: false

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: data
        uses: actions/checkout@v6
        with:
          repository: AICafe1/robusta-data
          token: ${{ secrets.PASS }}
          path: data

      - name: Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: mkdir csv; cd data; npm install

      - name: VSCode
        if: ${{ inputs.debug == true }}
        env:
          DNSE_KEY: ${{ secrets.DNSE_KEY }}
          DNSE_SEC: ${{ secrets.DNSE_SEC }}
          ZP: ${{ secrets.ZIP }}
        uses: fawazahmed0/action-debug-vscode@main

      - name: Download intraday
        env:
          DNSE_KEY: ${{ secrets.DNSE_KEY }}
          DNSE_SEC: ${{ secrets.DNSE_SEC }}
        run: |
          wget -qP csv https://github.com/AICafe1/robusta-server/releases/download/v1.0.1/metadata.zip
          unzip -qP ${{ secrets.ZIP }} csv/metadata.zip -d csv
          node data/download -m dat

      - name: Make zip
        shell: bash
        run: |
          cd csv
          find . -mindepth 3 -maxdepth 3 -type d -print0 | while IFS= read -r -d '' folder; do
            file=$(echo "${folder:2}" | sed 's/\//-/g')
            wget -q https://github.com/AICafe1/robusta-server/releases/download/v1.0.1/$file.zip
            zip -rqP ${{ secrets.ZIP }} $file.zip "${folder:2}/"
          done
          zip -qP ${{ secrets.ZIP }} metadata.zip *.json

      - name: Release v1.0.1
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v1.0.1
          working_directory: csv
          files: *.zip
