name: Intraday Data

on:
  schedule:
    - cron: '5 8 * * *'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: VSCode
        default: false

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      REPO: https://github.com/AICafe1/robusta-server/releases/download

    steps:
      - uses: actions/checkout@v6

      - name: data
        uses: actions/checkout@v6
        with:
          repository: AICafe1/robusta-data
          token: ${{ secrets.PASS }}
          path: data

      - name: src
        uses: actions/checkout@v6
        with:
          repository: AICafe1/robusta-src
          token: ${{ secrets.PASS }}
          path: src

      - name: Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: npm install; mkdir csv; cd data; npm install

      - name: VSCode
        if: ${{ inputs.debug == true }}
        env:
          DNSE_KEY: ${{ secrets.DNSE_KEY }}
          DNSE_SEC: ${{ secrets.DNSE_SEC }}
          ZP: ${{ secrets.ZIP }}
        uses: fawazahmed0/action-debug-vscode@main

      - name: Download intraday
        env:
          DNSE_KEY: ${{ secrets.DNSE_KEY }}
          DNSE_SEC: ${{ secrets.DNSE_SEC }}
        run: |
          [ -s csv/metadata.zip ] || wget -qP csv $REPO/v1.0.1/metadata.zip || true
          [ -s csv/metadata.zip ] || wget -qP csv $REPO/v1.0.3/metadata.zip
          unzip -qP ${{ secrets.ZIP }} csv/metadata.zip -d csv
          node data/download -m dat

      - name: Make zip
        run: |
          cd csv
          find . -mindepth 3 -maxdepth 3 -type d -print0 | while IFS= read -r -d '' folder; do
            echo $folder
            file=$(echo "${folder:2}" | sed 's/\//-/g')
            [ -s $file.zip ] || wget -q $REPO/v1.0.1/$file.zip || true
            [ -s $file.zip ] || wget -q $REPO/v1.0.3/$file.zip || true
            zip -ruqP ${{ secrets.ZIP }} $file.zip "${folder:2}/"
            rm -rf $folder
          done
          zip -qP ${{ secrets.ZIP }} metadata.zip *.json

      - name: Release v1.0.1
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v1.0.1
          working_directory: csv
          files: |
            *.zip

      - name: Release v1.0.3
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v1.0.3
          working_directory: csv
          files: |
            *.zip

      - name: Download intraday 2
        env:
          DNSE_KEY: ${{ secrets.DNSE_KEY }}
          DNSE_SEC: ${{ secrets.DNSE_SEC }}
        run: |
          rm csv/*.zip
          node data/download -m dat

      - name: Make zip 2
        run: |
          cd csv
          find . -mindepth 3 -maxdepth 3 -type d -print0 | while IFS= read -r -d '' folder; do
            echo $folder
            file=$(echo "${folder:2}" | sed 's/\//-/g')
            [ -s $file.zip ] || wget -q $REPO/v1.0.1/$file.zip || true
            [ -s $file.zip ] || wget -q $REPO/v1.0.3/$file.zip || true
            zip -ruqP ${{ secrets.ZIP }} $file.zip "${folder:2}/"
          done
          zip -qP ${{ secrets.ZIP }} metadata.zip *.json

      - name: Release v1.0.1 2
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v1.0.1
          working_directory: csv
          files: |
            *.zip

      - name: Release v1.0.3 2
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v1.0.3
          working_directory: csv
          files: |
            *.zip
