name: Minute Data

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: VSCode
        default: false

jobs:
  download:
    runs-on: ubuntu-latest

    env:
      REPO: https://github.com/AICafe1/robusta-server/releases/download

    steps:
      - name: data
        uses: actions/checkout@v6
        with:
          repository: AICafe1/robusta-data
          token: ${{ secrets.PASS }}

      - name: Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Pip
        run: pip install -q -r requirements.txt

      - name: Prepare data
        run: |
          wget -q $REPO/v25.5.7/index.txt
          YM=$(date -d "$(cat index.txt)-01 + 1 month" +%Y-%m)
          wget -q $REPO/v1.0.1/foreign-trading-$YM.zip
          wget -q $REPO/v1.0.1/trades-$YM.zip
          unzip -qP ${{ secrets.ZIP }} foreign-trading-$YM.zip
          unzip -qP ${{ secrets.ZIP }} trades-$YM.zip
          echo $YM > index.tx2
          if [[ "$(date -d "$YM-01 + 1 month + 7 days" +%Y-%m-%d)" < "$(date +%Y-%m-%d)" ]]; then
            echo $YM > index.txt
          fi
          rm *.zip

      - name: PreVSCode
        if: ${{ inputs.debug == true }}
        env:
          ZP: ${{ secrets.ZIP }}
        uses: dacdoan/action-debug-vscode@main

      - name: VSCode
        if: ${{ inputs.debug == true }}
        env:
          ZP: ${{ secrets.ZIP }}
        uses: fawazahmed0/action-debug-vscode@main

      - name: Build parquet
        run: python colab/dat/minute.py

      - name: Make zip
        run: |
          if [ -s minute.parquet ]; then
            YEAR=$(head -c4 index.tx2)
            YM=$(cat index.tx2)
            mv minute.parquet minute-$YM.parquet
            wget -q $REPO/v25.5.7/minute-$YEAR.zip || true
            zip -qP ${{ secrets.ZIP }} minute-$YEAR.zip minute-$YM.parquet
          fi

      - name: Release v25.5.7
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v25.5.7
          files: |
            minute-*.zip
            index.txt
