name: Minute Data

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: VSCode
        default: false

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      REPO: https://github.com/AICafe1/robusta-server/releases/download

    steps:
      - name: data
        uses: actions/checkout@v6
        with:
          repository: AICafe1/robusta-data
          token: ${{ secrets.PASS }}

      - name: Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Pip
        run: pip install -q -r requirements.txt

      - name: Prepare data
        run: |
          wget -q $REPO/v25.5.7/index.txt
          YM=$(date -d "$(cat index.txt)-01 + 1 month" +%Y-%m)
          if [[ "$(date -d "$YM-01 + 1 month + 9 days" +%Y-%m-%d)" < "$(date +%Y-%m-%d)" ]]; then
            wget -q $REPO/v1.0.1/foreign-trading-$YM.zip
            wget -q $REPO/v1.0.1/trades-$YM.zip
            echo $YM > index.txt
          fi

      - name: PreVSCode
        if: ${{ inputs.debug == true }}
        env:
          ZP: ${{ secrets.ZIP }}
        uses: dacdoan/action-debug-vscode@main

      - name: VSCode
        if: ${{ inputs.debug == true }}
        env:
          ZP: ${{ secrets.ZIP }}
        uses: fawazahmed0/action-debug-vscode@main
