name: Minute Data

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: VSCode
        default: false

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      REPO: https://github.com/AICafe1/robusta-server/releases/download

    steps:
      - name: data
        uses: actions/checkout@v6
        with:
          repository: AICafe1/robusta-data
          token: ${{ secrets.PASS }}

      - name: Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Pip
        run: pip install -q -r requirements.txt

      - name: PreVSCode
        if: ${{ inputs.debug == true }}
        env:
          ZP: ${{ secrets.ZIP }}
        uses: dacdoan/action-debug-vscode@main

      - name: VSCode
        if: ${{ inputs.debug == true }}
        env:
          ZP: ${{ secrets.ZIP }}
        uses: fawazahmed0/action-debug-vscode@main

      - name: Build parquet
        run: |
          wget -q $REPO/v25.5.7/index.txt
          UP=$(date -d "$(cat index.txt) +1 day" -u +%Y-%m-%d)
          if [[ "$UP" < "$(date -d "+15 hours" -u +%Y-%m-%d)" ]]; then
            YM=$(echo $UP | head -c7)
            wget -q $REPO/v1.0.1/foreign-trading-$YM.zip
            wget -q $REPO/v1.0.1/trades-$YM.zip
            unzip -qP ${{ secrets.ZIP }} foreign-trading-$YM.zip
            unzip -qP ${{ secrets.ZIP }} trades-$YM.zip
            rm *.zip
            python colab/dat/minute.py
            if [ -s minute.parquet ]; then
              YEAR=$(echo $UP | head -c4)
              mv minute.parquet minute-$YM.parquet
              wget -q $REPO/v25.5.7/minute-$YEAR.zip || true
              zip -qP ${{ secrets.ZIP }} minute-$YEAR.zip minute-$YM.parquet
            fi
            EOM=$(date -d "$YM-01 +1 month -1 day" -u +%Y-%m-%d)
            if [[ "$EOM" < "$(date -d "-9 hours" -u +%Y-%m-%d)" ]]; then
              echo $EOM > index.txt
            else
              echo $UP > index.txt
            fi
          fi

      - name: Release v25.5.7
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v25.5.7
          files: |
            minute-*.zip
            index.txt
